# Production Configuration for Model Garden Deployment
name: production-config

gcp:
  project_id: "falcon-deeptech-ai-stuff"  # Update with your production project
  region: "asia-southeast1"
  
model:
  name: "smolvlm-instruct"
  display_name: "SmolVLM-Instruct-Production"
  huggingface_id: "HuggingFaceTB/smolvlm-instruct"  # Note: lowercase for Model Garden
  
deployment:
  endpoint_name: "smolvlm-instruct-prod-endpoint"
  machine_type: "g2-standard-12"  # Larger for production
  accelerator_type: "NVIDIA_L4"
  accelerator_count: 1
  min_replica_count: 2  # Higher availability
  max_replica_count: 5
