# Development/Staging Configuration
name: staging-config

gcp:
  project_id: "falcon-deeptech-ai-stuff"  # Update with your staging project
  region: "asia-southeast1"
  
model:
  name: "smolvlm-instruct"
  display_name: "SmolVLM-Instruct-Staging"
  huggingface_id: "HuggingFaceTB/SmolVLM-Instruct"
  
deployment:
  endpoint_name: "smolvlm-instruct-staging-endpoint"
  machine_type: "g2-standard-8"  # Smaller for staging
  accelerator_type: "NVIDIA_L4"
  accelerator_count: 1
  min_replica_count: 1
  max_replica_count: 2
  
container:
  uri: "us-docker.pkg.dev/vertex-ai/prediction/pytorch-gpu.2-1.py310"
  environment_variables:
    TASK: "image-text-to-text"
    AIP_HEALTH_ROUTE: "/health"
    AIP_PREDICT_ROUTE: "/predict"
    AIP_HTTP_PORT: "8080"
    LOG_LEVEL: "DEBUG"
