# Development/Staging Configuration for Model Garden Deployment
name: staging-config

gcp:
  project_id: "falcon-deeptech-ai-stuff"  # Update with your staging project
  region: "asia-southeast1"  # Available regions: us-central1, us-east1, us-west1, europe-west1, europe-west4, asia-southeast1, asia-northeast1, asia-south1
  
model:
  name: "smolvlm-instruct"
  display_name: "SmolVLM-Instruct-Staging"
  huggingface_id: "HuggingFaceTB/smolvlm-instruct"  # Note: lowercase for Model Garden
  
deployment:
  endpoint_name: "smolvlm-instruct-staging-endpoint"
  machine_type: "g2-standard-8"  # Smaller for staging
  accelerator_type: "NVIDIA_L4"
  accelerator_count: 1
  min_replica_count: 1
  max_replica_count: 2
